site_name: cookiecutter-uv
repo_url: https://github.com/sahma19/cookiecutter-uv
site_url: https://sahma19.github.io/cookiecutter-uv
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: sahma19
edit_uri: edit/main/docs/
repo_name: sahma19/cookiecutter-uv
copyright: Maintained by <a href="https://sahma19.com">sahma19</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["cookiecutter_uv"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sahma19/cookiecutter-uv
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cookiecutter-uv

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
